name: test-priv-registry

on:
  push:
    branches: [ main ]

jobs:
  run_pv_docker_image:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "asd $SSH_KEY asd" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.PASS}}
      - run: 'cat key | base64 '
        shell: bash
