name: test-priv-registry

on:
  push:
    branches: [ main ]

jobs:
  run_pv_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: |
          echo "aaa ${{ secrets.pass}} aaa" > a.txt | cat a.txt
